spring.application.name=banking-system
server.port=8080

# DataSource (sobrescrito por variables de entorno en docker-compose)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banco}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:banco_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:banco_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
